### PR TITLE
Changes default development IP to 127.0.0.1

### PR DESCRIPTION
**Pull request by schalkventer**
**What kind of change does this PR introduce?**

Changes default development IP to `127.0.0.1`

**Did you add tests for your changes?**

No.

**Summary**

The current default, `0.0.0.0` does not work on Windows machines.

**Does this PR introduce a breaking change?**

No.

### CODE REVIEW

**Comment by schalkventer** [comment]
@ForsakenHarmony @developit Seems that even when it is not `0.0.0.0` it does not work on Windows, however going `localhost` seems to do the trick.

Can we perhaps set the default to `localhost`? Let me know what you think?

image

**Comment by rosenbjerg** [comment]
I've never had that problem on Windows.
Does this happen when just running yarn dev?

**Comment by schalkventer** [comment]
@rosenbjerg Yeah.

**Comment by schalkventer** [comment]
@developit @ForsakenHarmony any update on this?

Seems like a minor change?

**Comment by ForsakenHarmony** [comment]
@schalkventer just noticed this might have been fixed by #1171

**Comment by schalkventer** [comment]
Thanks @ForsakenHarmony. I'll give this a try and let you know.

**Pull request merged**
