### PR TITLE
Reduce bundle size in esm-mode by 7.5kb by using native-url

### PR DESCRIPTION
**Pull request by JoviDeCroock**
**What kind of change does this PR introduce?**

A feature

**Did you add tests for your changes?**

No tests, can I test this?

**Summary**

We can reduce 7.5 kb by switching out the webpack url polyfill for [native-url](https://github.com/GoogleChromeLabs/native-url)

Note: The GH-actions aren't added to `branch-protection` yet so we can just merge without them running

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
Thought we already did this before 🤔

**Comment by lukeed** [comment]
What pieces of `url` are in use?

**Comment by prateekbh** [comment]
cc: @janicklas-ralph

**Comment by prateekbh** [comment]
Quick question: if we don't do this, do we ship some other  bigger polyfill via Babel?

**Comment by lukeed** [comment]
Yes, webpack's

**Comment by prateekbh** [comment]
@lukeed, always or when we use `URL`  in the application code?

**Comment by lukeed** [comment]
When `'url'` is used

**Comment by lukeed** [comment]
Although this seems to be the only place that it's used? https://github.com/preactjs/preact-cli/blob/86b530df20cd06baa890a0c9488bc504ad921db0/packages/cli/lib/lib/webpack/prerender.js#L5

That shouldnt be included in webpack bundle... not sure what's going on

**Comment by janicklas-ralph** [comment]
No issues on `native-url` at the moment. 

NextJS has also been using it for sometime.

**Comment by prateekbh** [comment]
@jovidecroock why with env.esm tho?

**Comment by JoviDeCroock** [comment]
@prateekbh it should only be safe to use in modern mode

**Comment by JoviDeCroock** [comment]
> @JoviDeCroock based on your last comment [#1040 (comment)](https://github.com/preactjs/preact-cli/pull/1040#issuecomment-598118172), this has to be placed here: https://github.com/preactjs/preact-cli/blob/master/packages/cli/lib/lib/webpack/webpack-client-config.js#L154

Can we change stuff for webpack through that babel-plugin? That would feel kinda odd, I could check for that env variable as well in webpack?

**Comment by prateekbh** [comment]
^ its just a hook if u wanna make extra changes in the child compilation. Usually changing definitions  upfront would leak them to parent compiler.

**Comment by JoviDeCroock** [comment]
Hey @prateekbh I just noticed this is available on every browser https://caniuse.com/#feat=mdn-api_url

**Pull request merged**
