### PR TITLE
feat: alias compat for preact X

### PR DESCRIPTION
**Pull request by ForsakenHarmony**

### CODE REVIEW

**Comment by prateekbh** [comment]
do we need compat for X?

**Comment by ForsakenHarmony** [comment]
wdym?

**Comment by prateekbh** [comment]
i thought all the stuff in compat are now directly in `preactX` so we can alias them directly to `preact`

**Comment by ForsakenHarmony** [comment]
no? 👀

**Comment by prateekbh** [comment]
ohhh i might be completely wrong here

**Comment by ForsakenHarmony** [comment]
it's now in the main package imported as `preact/compat`, but it's still a thing to keep core small

**Pull request merged**
