### PR TITLE
fix: Correcting create command finished instructions

### PR DESCRIPTION
**Pull request by rschristian**
**What kind of change does this PR introduce?**

Bugfix

**Did you add tests for your changes?**

No

**Summary**

The CLI's `create` command is supposed to output some instructions to users upon completing. However, this is broken on the latest version, and looks to have been broken years ago. Was just hidden while everyone was still using `2.2.1` for their global installs. 

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Review by jamesgeorge007 — APPROVED** [review]

**Review by ForsakenHarmony — APPROVED** [review]

**Comment by ForsakenHarmony** [comment]
bors retry

**Comment by ForsakenHarmony** [comment]
bors try-

**Pull request merged**
