### PR TITLE
Inline CSS fixes

### PR DESCRIPTION
**Pull request by prateekbh**
**To be merged after: https://github.com/GoogleChromeLabs/critters/pull/45**

**What kind of change does this PR introduce?**
Bug fix

**Did you add tests for your changes?**
Updated the existing tests

**Summary**
Critters only inlines the css from the css files actually present in the html.
This was the reason why home page's css was never inlined on http://cli-demo-next.preactjs.com
This PR adds route's css as well as bundle css

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by prateekbh** [comment]
Ahhh problem!
We always pre-render home, which means for someone who points all routes to `/` there will always be extra css loaded via `route-home.chunk.css`

**Comment by prateekbh** [comment]
Like deploy to surge and redirect * to /

**Comment by ForsakenHarmony** [comment]
Oh you're talking about the backend always serving `/index.html`, not the route specific html files

**Comment by prateekbh** [comment]
yep, in that case all routes will download an extra `route-home.chunk.xxxxx.css`

**Comment by prateekbh** [comment]
// @developit: ^ request for additional stylesheets options in critters

**Comment by prateekbh** [comment]
@developit @ForsakenHarmony can this be solved by skipping css code splitting for server build?

**Comment by prateekbh** [comment]
also may be skip terser for server bundle for speeding up builds?

**Pull request merged**
