### PR TITLE
fix: output css source map

### PR DESCRIPTION
**Pull request by teodragovic**
**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

no

**Summary**

https://github.com/preactjs/preact-cli/issues/1793

**Does this PR introduce a breaking change?**

no

### CODE REVIEW

**Comment by teodragovic** [comment]
Is filesize some random value or should I produce build to get it? If latter, how do I do it? Just run clean installation?

**Comment by rschristian** [comment]
You'll need to run a build to get it. The test ensures that file is +/5% of the listed value.

Unfortunately it's a bit of a pain in the ass to generate, could never figure out a way to automate it. Easiest way is to only run the one build test and get the file size from the directory that's created.

**Comment by rschristian** [comment]
I'll take care of it in a few minutes, it's a faff

**Review by rschristian — APPROVED** [review]
Thanks for catching this, tracking down the solution, AND implementing! I really appreciate it!

**Pull request merged**
